name: Hello Server CI

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build for Linux
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

